# Generated by Django 4.2.5 on 2024-05-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coinsdata",
            name="total_coins",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
