# Generated by Django 4.2.5 on 2024-06-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_coinsdata_total_coins"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(default="", max_length=500)),
                ("title", models.CharField(default="Privacy Policy", max_length=20)),
            ],
        ),
    ]
